[package]
name = "transport"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.5.0"
log = "0.4.20"
rmp-serde = "1.1.2"
serde = { version = "1.0.195", features = ["derive"] }
common = { path = "../common" }
thiserror = "1.0.56"
rand = "0.8"
socket2 = "0.5.6"
crc = "3.0.1"
thread-priority = "0.16.0"
xxhash-rust = { version = "0.8.5", features = ["xxh3"]}

[[example]]
name = "simple"

[dev-dependencies]
clap = { version = "4", features = ["derive", "env"] }
anyhow = "1.0.79"
simple_logger = "4"
