[package]
name = "native"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "mirror_android"

[dependencies]
bytes = "1.5"
transport = { path = "../../../transport"}
log = { version = "0.4.20", features = ["std"]}
num_cpus = "1.16.0"
jni = "0.21.1"
common = { path = "../../../common"}
anyhow = "1.0.79"
jni-macro = { path = "../../../common/jni-macro" }
